#CHISQUARE Test

State the Hypotheses

`Null Hypothesis (H₀)`: No association between device type and customer satisfaction

`Alternative Hypothesis (H₁)`: There is an association between device type and customer satisfaction


In [15]:
# input the observed frequencies from the contingency table and calculate
#expected frequencies assuming independence
import numpy as np
import pandas as pd
from scipy.stats import chi2

# Observed frequencies
observed = np.array([[50, 70], [80, 100],[60, 90],[30, 50],[20, 50]
])

In [16]:
# Row and column totals
row_totals = observed.sum(axis=1)
row_totals

array([120, 180, 150,  80,  70])

In [17]:
col_totals = observed.sum(axis=0)
col_totals

array([240, 360])

In [18]:
grand_total = observed.sum()
grand_total

np.int64(600)

In [19]:
# Expected frequencies
expected = np.outer(row_totals, col_totals) / grand_total
expected


array([[ 48.,  72.],
       [ 72., 108.],
       [ 60.,  90.],
       [ 32.,  48.],
       [ 28.,  42.]])

In [20]:
# Chi-square statistic
chi_square_stat = ((observed - expected) ** 2 / expected).sum()
chi_square_stat = round(chi_square_stat, 2)

In [21]:
chi_square_stat

np.float64(5.64)

 Determine the Critical Value

In [22]:
# Degrees of freedom: (rows - 1) * (columns - 1)
df = (5 - 1) * (2 - 1)
alpha = 0.05

In [23]:
# Critical value from chi-square distribution
critical_value = round(chi2.ppf(1 - alpha, df), 2)
critical_value

np.float64(9.49)

 Make a Decision

In [24]:
# If the statistic is greater than the critical value, we reject the null hypothesis.
# If it is less, we accept the null hypothesis.

if chi_square_stat > critical_value:
    conclusion = "Reject the null hypothesis: There is a significant association."
else:
    conclusion = "accept the null hypothesis: No significant association."

conclusion

'accept the null hypothesis: No significant association.'

#HYPOTHESIS

`Null Hypothesis (H₀)`:The weekly operating cost follows the theoretical model (W = $1,000 + $5X).  
`Alternative Hypothesis (H₁)`:The actual weekly operating cost is higher than the theoretical model.


Calculate the Test Statistic:

Use the following formula to calculate the test statistic (t):

where:
*   ˉxˉ = sample mean weekly cost (Rs. 3,050)
*   μ = theoretical mean weekly cost according to the cost model (W = $1,000 + $5X for X = 600 units)
*   σ = 5*25 units
*   n = sample size (25 restaurants)


In [25]:
import math

# Given values
sample_mean = 3050
theoretical_mean = 1000 + 5 * 600
std_dev = 5 * 25
n = 25

In [26]:
# Test statistic
t_stat = (sample_mean - theoretical_mean) / (std_dev / math.sqrt(n))
t_stat = round(t_stat, 2)
t_stat

-38.0

Determine the Critical Value

In [27]:
from scipy.stats import norm
alpha = 0.05
critical_value = round(norm.ppf(1 - alpha), 2)
critical_value

np.float64(1.64)

In [28]:
#Make a Decision
if t_stat > critical_value:
    decision = "Reject the null hypothesis: There is strong evidence that actual costs are higher."
else:
    decision = "accept the null hypothesis: No strong evidence that actual costs are higher."

print(decision)

accept the null hypothesis: No strong evidence that actual costs are higher.


# Conclusion:
Based on the association rule mining using the FP-Growth algorithm, several meaningful and strong relationships between products were identified. The discovered rules reveal clear purchasing patterns, such as customers who buy ground beef and mineral water are highly likely to also purchase spaghetti, indicating common meal-planning behavior. These insights can help retailers optimize product placement, cross-selling strategies, promotional bundling, and inventory management. Overall, the results demonstrate that FP-Growth effectively uncovers hidden patterns in large transactional datasets and provides valuable business intelligence for decision-making.